### ISSUE TITLE
Can we add open more option to check the number of elements available in present model.

### ISSUE THREAD

**Issue by ashwanidv100** [TorsionTools/R20#2]
The user form has a dropdown of Built-in category list (similar to Dynamo 'Category' node ) and by submitting the choice of category user can get the output such as Number of elements present of chosen category and more (can be added later such as the list of element Ids and some relevant details or element warnings). This is also a good example to explore Combobox and built-in collection use case.

**Comment by TorsionTools** [comment]
I have added the Family Instances of Category command on the Tools panel. This will allow you to select a category and will return information like Element Id, Name, Level for all placed instances of that category. If you click on a row in the DataGridView, the Element identified in that row will become the current selection.
