### ISSUE TITLE
RevitAPI & RevitAPIUI copy local

### ISSUE THREAD

**Issue by truevis** [TorsionTools/R20#3]
Shouldn't they both have _Copy Local_ set to False?
![image](https://user-images.githubusercontent.com/3574046/72327221-3dc4b880-36e3-11ea-9eae-15aaa6d1fcc2.png)

**Comment by TorsionTools** [comment]
Thank you @truevis for your feedback, and yes for a production / release build this would be correct. We were seeing issues when someone Downloaded the repository it was breaking the References so I included them to help resolve. They both will be set to back to False.
